trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - infrastructure/*
    - src/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: variables/development.yml
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'

stages:
  - stage: development
    variables:
      - template: variables/development.yml
      
    jobs:
      - job: deploy_landing_zone                
        steps:
          - template: steps/lz-steps.yml
            parameters:
              armPath: '$(infrastructurePath)'

  - stage: production
    variables:
      - template: variables/production.yml
    jobs:
      - job: deploy_landing_zone
        steps:
          - template: steps/lz-steps.yml
            parameters:
              armPath: '$(infrastructurePath)'