variables:
  - template: common.yml  
  - name: Environment
    value: 'Production'
  - name: rgName
    value: 'rg-jmassick-prod-001'
  - name: locationName
    value: 'West US 2'
  - name: 'appInsightsName'
    value: 'appi-jmassick-prod-001'
  - name: 'kvName'
    value: 'kv-jmassick-prod-001'
  - name: storageName
    value: 'stjmassickprod001'
  - name: workspaceName
    value: 'work-jmassick-prod-001'
  - name: cognitiveServicesName
    value: 'cog-jmassick-prod-001'